# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml.
# All the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "nuKardex"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# When the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
   template_toolkit:
      encoding: 'utf-8'
      start_tag: '[%'
      end_tag:   '%]'

# For session support enable the following line and see Dancer::Session
# session: "YAML"
session: "YAML"
session_dir: "sessions"

username: 'username'
password: 'password'

demousername:  'demo'
demouser_email: 'my@email.com'

testing:
   disable_authentication: 0

aleph_x_server: 'https://aleph21/X'
aleph_adm_library: 'USM50'
aleph_logical_base: 'USM01'
aleph_user_name: 'WWW-X'
aleph_user_password: 'WWW-X'

barcode_seed: 5551000000

mailer:
   subject: 'Journal issue claim'
   sender: 'my@email.com'
   cc: 'my@email.com'
   tz: 'Europe/Copenhagen'
   # If SMTP is undefined local delivery will be used
   smtp: 'mailhost'

plugins:
   Database:
      driver: SQLite
      database: 'db/nuKardex.sqlite'
      log_queries: 1
      dbi_params:
         RaiseError: 1
         AutoCommit: 1
